### PR TITLE
comments to exercises/2.1/script.js

### PR DESCRIPTION
**Pull request by renatdd**
Exercício 2.2 - Adicionando comentário.

### CODE REVIEW

**Comment by LeonarDev** [comment]
You can solve the conflicts choosing one of the commits and go to the next step.
Good job! 
That's it.

**Comment by fcbresende** [comment]
Tudo certinho, #VQV

**Comment by DanrlleyR** [comment]
Filé, vamo que vamo \o/

**Comment by KevinFraga** [comment]
Go Trybe! VQV!!

**Comment by negres** [comment]
Muito bom!
#VQV meu fi :man_technologist:

**Comment by jdaniel-ap** [comment]
blz #VQV

**Pull request merged**
